export const testStatusEnum = {
  STARTED: "STARTED",
  NOT_STARTED: "NOT_STARTED",
  COMPLETED: "COMPLETED",
  ABANDONED: "ABANDONED"
};

export const testTypeEnum = {
  SUBJECT_TEST: "SUBJECT_TEST",
  SUBJECT_RETEST: "SUBJECT_RETEST"
};
